[build]
publish = "build" # or "dist" if that's your output folder
command = "" # leave empty since you don’t need a build step for plain HTML

[dev]
command = "npm run start"
port = 8888
publish = "build"
